import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, InlineMessage } from '../../design-system/components';
import './VideoPromptProfilesAdmin.css';

type Profile = { id:string; profileKey:string; displayName:string; publicDescription:string; visualKey:string; active:boolean; public:boolean; displayOrder:number; currentVersionId:string; currentVersion:number; checksum:string; version:number; baseSystemPrompt:string; executionTemplate:string; rulesManifest:Record<string,unknown> };
type ProfileVersion = { id:string; version:number; checksum:string; createdByAdminId:string|null; changeReason:string; createdAt:string; jobCount:number };
type Audit = { id:number; profileKey:string; action:string; changedBy:string; reason:string; createdAt:string };
type Preview = { profileKey:string; profileVersion:number; compilerVersion:string; userPrompt:string; compiledPrompt:string; compiledPromptHash:string };

async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`/api/admin/video-prompt-profiles${path}`,{credentials:'include',cache:'no-store',...init,headers:{...(init?.body?{'Content-Type':'application/json'}:{}),...init?.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.message||body?.error||'عملیات ناموفق بود.');return body as T;}

export default function VideoPromptProfilesAdmin(){
  const [profiles,setProfiles]=useState<Profile[]>([]); const [selectedKey,setSelectedKey]=useState(''); const [versions,setVersions]=useState<ProfileVersion[]>([]); const [audits,setAudits]=useState<Audit[]>([]);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [reason,setReason]=useState('');
  const [draft,setDraft]=useState<Profile|null>(null); const [basePrompt,setBasePrompt]=useState(''); const [template,setTemplate]=useState(''); const [rulesJson,setRulesJson]=useState(''); const [previewInput,setPreviewInput]=useState('شخص آرام سرش را برگرداند و لبخند بزند'); const [preview,setPreview]=useState<Preview|null>(null);
  const selected=useMemo(()=>profiles.find((profile)=>profile.profileKey===selectedKey)||profiles[0]||null,[profiles,selectedKey]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [profileData,auditData]=await Promise.all([api<{items:Profile[]}>(''),api<{items:Audit[]}>('/audit')]);setProfiles(profileData.items);setAudits(auditData.items);setSelectedKey((value)=>profileData.items.some((item)=>item.profileKey===value)?value:profileData.items[0]?.profileKey||'');}catch(cause){setError(cause instanceof Error?cause.message:'دریافت پروفایل‌ها ناموفق بود.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!selected)return;setDraft({...selected});setBasePrompt(selected.baseSystemPrompt);setTemplate(selected.executionTemplate);setRulesJson(JSON.stringify(selected.rulesManifest,null,2));setPreview(null);void api<{items:ProfileVersion[]}>(`/${encodeURIComponent(selected.profileKey)}/versions`).then((data)=>setVersions(data.items)).catch((cause)=>setError(cause instanceof Error?cause.message:'دریافت نسخه‌ها ناموفق بود.'));},[selected?.profileKey,selected?.version]);
  const done=(text:string)=>{setMessage(text);setError('');setReason('');void load();};
  const updateMetadata=async()=>{if(!draft||reason.trim().length<5)return;setSaving(true);try{await api(`/${encodeURIComponent(draft.profileKey)}`,{method:'PATCH',body:JSON.stringify({expectedVersion:draft.version,reason,displayName:draft.displayName,publicDescription:draft.publicDescription,visualKey:draft.visualKey,active:draft.active,public:draft.public,displayOrder:draft.displayOrder})});done('اطلاعات عمومی پروفایل ثبت و ممیزی شد.');}catch(cause){setError(cause instanceof Error?cause.message:'ثبت تغییر ناموفق بود.');}finally{setSaving(false);}};
  const createVersion=async()=>{if(!draft||reason.trim().length<5)return;let rulesManifest:Record<string,unknown>;try{rulesManifest=JSON.parse(rulesJson);}catch{setError('Rules Manifest باید JSON معتبر باشد.');return;}if(!window.confirm('نسخه جدید ساخته شود؟ نسخه‌های قبلی تغییر نمی‌کنند.'))return;setSaving(true);try{await api(`/${encodeURIComponent(draft.profileKey)}/versions`,{method:'POST',body:JSON.stringify({expectedVersion:draft.version,reason,baseSystemPrompt:basePrompt,executionTemplate:template,rulesManifest})});done('نسخه جدید Prompt ساخته و فعال شد.');}catch(cause){setError(cause instanceof Error?cause.message:'ساخت نسخه ناموفق بود.');}finally{setSaving(false);}};
  const compilePreview=async()=>{if(!draft)return;setSaving(true);try{setPreview(await api<Preview>(`/${encodeURIComponent(draft.profileKey)}/compile-preview`,{method:'POST',body:JSON.stringify({userPrompt:previewInput,settings:{duration:5,resolution:'720p',aspectRatio:'9:16',generateAudio:false}})}));setError('');}catch(cause){setError(cause instanceof Error?cause.message:'Preview ناموفق بود.');}finally{setSaving(false);}};

  return <section className="video-profiles-admin" dir="rtl" aria-labelledby="video-profiles-title"><header><div><p>VIDEO PROMPT PROFILES</p><h2 id="video-profiles-title">پروفایل‌های ساخت ویدیو</h2><span>مدیریت نسخه‌ای قواعد سینمایی و انیمیشنی؛ Preview کاملاً محلی است.</span></div><Button variant="secondary" onClick={()=>void load()} disabled={loading}>به‌روزرسانی</Button></header>{message?<InlineMessage variant="success" text={message}/>:null}{error?<InlineMessage variant="error" text={error}/>:null}
    {loading?<p role="status">در حال دریافت پروفایل‌ها…</p>:<div className="video-profiles-layout"><nav aria-label="پروفایل‌های ویدیو">{profiles.map((profile)=><button key={profile.profileKey} type="button" aria-current={selected?.profileKey===profile.profileKey?'true':undefined} className={selected?.profileKey===profile.profileKey?'is-active':''} onClick={()=>setSelectedKey(profile.profileKey)}><strong>{profile.displayName}</strong><small>v{profile.currentVersion} · {profile.active&&profile.public?'عمومی':'محدود'}</small></button>)}</nav>
      {draft?<div className="video-profiles-content"><section className="video-profile-card"><h3>اطلاعات عمومی و وضعیت</h3><div className="video-profile-fields"><label><span>عنوان عمومی</span><input value={draft.displayName} onChange={(e)=>setDraft({...draft,displayName:e.target.value})}/></label><label><span>توضیح عمومی</span><textarea rows={3} value={draft.publicDescription} onChange={(e)=>setDraft({...draft,publicDescription:e.target.value})}/></label><label><span>Visual key</span><input dir="ltr" value={draft.visualKey} onChange={(e)=>setDraft({...draft,visualKey:e.target.value})}/></label><label><span>ترتیب نمایش</span><input type="number" value={draft.displayOrder} onChange={(e)=>setDraft({...draft,displayOrder:Number(e.target.value)})}/></label><div className="video-profile-checks"><label><input type="checkbox" checked={draft.active} onChange={(e)=>setDraft({...draft,active:e.target.checked})}/> فعال</label><label><input type="checkbox" checked={draft.public} onChange={(e)=>setDraft({...draft,public:e.target.checked})}/> عمومی</label></div></div><label className="video-profile-reason"><span>دلیل تغییر</span><input value={reason} minLength={5} maxLength={500} onChange={(e)=>setReason(e.target.value)} placeholder="دلیل قابل پیگیری"/></label><Button disabled={saving||reason.trim().length<5} onClick={()=>void updateMetadata()}>ثبت اطلاعات عمومی</Button></section>
        <section className="video-profile-card"><div className="video-profile-title"><h3>نسخه جاری Prompt</h3><code dir="ltr">SHA-256: {draft.checksum}</code></div><label><span>System Prompt کامل</span><textarea className="video-profile-prompt" rows={12} value={basePrompt} onChange={(e)=>setBasePrompt(e.target.value)}/></label><label><span>Execution Template</span><textarea rows={5} dir="ltr" value={template} onChange={(e)=>setTemplate(e.target.value)}/></label><label><span>Rules Manifest JSON</span><textarea className="video-profile-json" rows={12} dir="ltr" value={rulesJson} onChange={(e)=>setRulesJson(e.target.value)}/></label><p>ذخیره این بخش همیشه Version جدید می‌سازد و Jobهای قبلی را تغییر نمی‌دهد.</p><Button disabled={saving||reason.trim().length<5} onClick={()=>void createVersion()}>ساخت نسخه جدید</Button></section>
        <section className="video-profile-card"><h3>Preview محلی Compiler</h3><label><span>User Prompt آزمایشی</span><textarea rows={3} value={previewInput} onChange={(e)=>setPreviewInput(e.target.value)}/></label><Button variant="secondary" disabled={saving||previewInput.trim().length<3} onClick={()=>void compilePreview()}>Compile بدون Provider</Button>{preview?<div className="video-profile-preview"><div><span>Profile</span><code>{preview.profileKey} v{preview.profileVersion}</code></div><div><span>Compiler</span><code>v{preview.compilerVersion}</code></div><div><span>Hash</span><code dir="ltr">{preview.compiledPromptHash}</code></div><pre dir="ltr">{preview.compiledPrompt}</pre></div>:null}</section>
        <section className="video-profile-card"><h3>نسخه‌ها و Jobهای وابسته</h3><div className="video-profile-table"><table><thead><tr><th>نسخه</th><th>Checksum</th><th>Job</th><th>دلیل</th><th>زمان</th></tr></thead><tbody>{versions.map((item)=><tr key={item.id}><td>v{item.version}</td><td><code dir="ltr">{item.checksum.slice(0,12)}…</code></td><td>{item.jobCount}</td><td>{item.changeReason}</td><td>{new Date(item.createdAt).toLocaleString('fa-IR')}</td></tr>)}</tbody></table></div></section>
        <section className="video-profile-card"><h3>Audit</h3><div className="video-profile-table"><table><thead><tr><th>پروفایل</th><th>عملیات</th><th>مدیر</th><th>دلیل</th><th>زمان</th></tr></thead><tbody>{audits.map((item)=><tr key={item.id}><td>{item.profileKey}</td><td>{item.action}</td><td>{item.changedBy}</td><td>{item.reason}</td><td>{new Date(item.createdAt).toLocaleString('fa-IR')}</td></tr>)}</tbody></table></div></section>
      </div>:null}</div>}
  </section>;
}

