CREATE TABLE IF NOT EXISTS input_optimizations (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  operation_type VARCHAR(64) NOT NULL,
  operation_id VARCHAR(191) NOT NULL,
  conversation_id VARCHAR(191) NULL,
  turn_id VARCHAR(64) NULL,
  attempt_id VARCHAR(64) NULL,
  image_generation_id BIGINT NULL,
  user_id VARCHAR(191) NULL,
  guest_id VARCHAR(64) NULL,
  original_input MEDIUMTEXT NOT NULL,
  optimized_input MEDIUMTEXT NULL,
  source_language VARCHAR(16) NULL,
  target_language VARCHAR(16) NOT NULL DEFAULT 'en',
  ambiguity_level ENUM('none','low','high') NOT NULL DEFAULT 'none',
  needs_clarification TINYINT(1) NOT NULL DEFAULT 0,
  clarification_question_fa TEXT NULL,
  status ENUM('pending','completed','clarification_required','fallback','failed','cancelled','disabled') NOT NULL DEFAULT 'pending',
  model VARCHAR(191) NULL,
  optimizer_version VARCHAR(32) NOT NULL DEFAULT '1',
  latency_ms INT NULL,
  retry_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  fallback_used TINYINT(1) NOT NULL DEFAULT 0,
  error_code VARCHAR(100) NULL,
  metadata JSON NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  UNIQUE KEY uq_input_optimizations_operation (operation_type, operation_id),
  INDEX idx_input_optimizations_user_created (user_id, created_at),
  INDEX idx_input_optimizations_conversation_created (conversation_id, created_at),
  INDEX idx_input_optimizations_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
