'use strict';

const assert = require('node:assert/strict');
const { test } = require('node:test');
const {
  detectImageMime,
  validateImageBuffer,
  safeProviderImageFilename
} = require('./image-file-security');

const PNG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00]);
const JPEG = Buffer.from([0xff, 0xd8, 0xff, 0xdb, 0x00]);
const WEBP = Buffer.from('RIFFxxxxWEBPxxxx', 'ascii');

test('detects supported image signatures', () => {
  assert.equal(detectImageMime(PNG), 'image/png');
  assert.equal(detectImageMime(JPEG), 'image/jpeg');
  assert.equal(detectImageMime(WEBP), 'image/webp');
});

test('rejects fake image content even when mime claims png', () => {
  assert.throws(
    () => validateImageBuffer(Buffer.from('<script>alert(1)</script>'), 'image/png'),
    (error) => error?.code === 'UNSUPPORTED_IMAGE_FORMAT'
  );
});

test('rejects a mismatched claimed mime type', () => {
  assert.throws(
    () => validateImageBuffer(PNG, 'image/jpeg'),
    (error) => error?.code === 'UNSUPPORTED_IMAGE_FORMAT'
  );
});

test('provider filename is generated by the server and ignores user input', () => {
  assert.equal(safeProviderImageFilename('image/png', 0), 'danoa-image-1.png');
  assert.equal(safeProviderImageFilename('image/jpeg', 2), 'danoa-image-3.jpg');
});
