process.env.NODE_ENV = 'test';
const test = require('node:test'); const assert = require('node:assert/strict'); const mysql = require('mysql2/promise'); const path = require('node:path'); const { execFileSync } = require('node:child_process'); const { randomUUID } = require('node:crypto');
require('dotenv').config({ path: path.join(__dirname, '../../../../.env') });
const { createVideoWorkerRepository } = require('../worker/video-worker.repository'); const { createVideoJobProcessingService } = require('../worker/video-job-processing.service'); const { createVideoGenerationWorker } = require('../worker/video-generation.worker'); const { createVideoWorkerRuntime } = require('../worker/video-worker.runtime'); const { createFakeVideoProvider } = require('../providers/fake-video.provider');
let pool; const ids = new Set(); const runtimes = new Set(); const config = Object.freeze({ enabled: true, processMode: 'embedded', runImmediately: false, intervalMs: 1000, shutdownTimeoutMs: 100, leaseMs: 1000, batchSize: 2, jobTimeoutMinutes: 30, maxPollAttempts: 3, pollBaseDelayMs: 50, pollMaxDelayMs: 100 });
const id = (p) => { const x = `${p}-${randomUUID()}`; ids.add(x); return x; }; const q = (sql, params) => pool.query(sql, params);
async function fixture({ status = 'submitted', expires = 'DATE_ADD(NOW(), INTERVAL 1 HOUR)' } = {}) { const userId = id('runtime-user'), planId = id('runtime-plan'), modelKey = id('runtime-model').slice(0, 64), jobId = id('runtime-job'), reservationId = id('runtime-res'), providerJobId = id('runtime-provider'), periodKey = '2099-12'; await q('INSERT INTO app_users (user_id,name,age,registered_at) VALUES (?,?,20,NOW())', [userId, 'Runtime']); await q('INSERT INTO app_plans (id,name,features,is_active,created_at,updated_at) VALUES (?,?,JSON_ARRAY(),0,NOW(),NOW())', [planId, 'Runtime']); await q("INSERT INTO app_video_models (internal_key,provider,provider_model_id,display_name_fa,is_active,supports_text_to_video,supports_image_to_video,allowed_aspect_ratios,allowed_durations,allowed_qualities,max_prompt_length,quota_units,created_at,updated_at) VALUES (?,?,?,'مدل',0,1,0,JSON_ARRAY('16:9'),JSON_ARRAY('4'),JSON_ARRAY('standard'),100,1,NOW(),NOW())", [modelKey, 'fake', 'fake']); await q('INSERT INTO app_video_usage (user_id,period_key,video_used,video_reserved,updated_at) VALUES (?,?,0,1,NOW())', [userId, periodKey]); await q(`INSERT INTO app_video_generations (id,user_id,mode,model_key,provider,provider_model_id_snapshot,status,prompt,aspect_ratio,duration,quality,provider_job_id,quota_units,quota_reservation_id,idempotency_hash,payload_hash,expires_at,next_poll_at,created_at,updated_at) VALUES (?,?,'text-to-video',?,'fake','fake',?,'fixture','16:9','4','standard',?,1,?,SHA2(UUID(),256),SHA2(UUID(),256),${expires},NOW(),NOW(),NOW())`, [jobId, userId, modelKey, status, providerJobId, reservationId]); await q("INSERT INTO app_video_quota_reservations (id,user_id,period_key,generation_id,quota_units,status,created_at,updated_at) VALUES (?,?,?,?,1,'reserved',NOW(),NOW())", [reservationId, userId, periodKey, jobId]); return { userId, jobId, reservationId, providerJobId, periodKey }; }
async function state(f) { const [[job]] = await q('SELECT * FROM app_video_generations WHERE id=?', [f.jobId]); const [[usage]] = await q('SELECT * FROM app_video_usage WHERE user_id=? AND period_key=?', [f.userId, f.periodKey]); return { job, usage }; }
async function cleanup() { for (const x of ids) { await q('DELETE FROM app_video_quota_reservations WHERE id=?', [x]); await q('DELETE FROM app_video_generations WHERE id=?', [x]); await q('DELETE FROM app_video_models WHERE internal_key=?', [x]); await q('DELETE FROM app_video_usage WHERE user_id=?', [x]); await q('DELETE FROM app_plans WHERE id=?', [x]); await q('DELETE FROM app_users WHERE user_id=?', [x]); } ids.clear(); }
async function purgeInterruptedFixtures() { await q("DELETE r FROM app_video_quota_reservations r INNER JOIN app_video_generations g ON g.id=r.generation_id WHERE g.id LIKE 'runtime-job-%'"); await q("DELETE FROM app_video_generations WHERE id LIKE 'runtime-job-%'"); await q("DELETE FROM app_video_models WHERE internal_key LIKE 'runtime-model-%'"); await q("DELETE FROM app_video_usage WHERE user_id LIKE 'runtime-user-%'"); await q("DELETE FROM app_plans WHERE id LIKE 'runtime-plan-%'"); await q("DELETE FROM app_users WHERE user_id LIKE 'runtime-user-%'"); }
function runtime(provider, owner = `runtime-${randomUUID().slice(0, 8)}`) { const repository = createVideoWorkerRepository(pool); const processingService = createVideoJobProcessingService({ repository, providerRegistry: { fake: provider }, config }); const value = createVideoWorkerRuntime({ config, workerDependencies: { repository, processingService, config, workerId: owner }, createWorker: createVideoGenerationWorker }); runtimes.add(value); return value; }
test.before(async () => { execFileSync(process.execPath, ['scripts/apply-video-generation-migration.js'], { cwd: path.join(__dirname, '../../../..'), stdio: 'inherit' }); const u = new URL(process.env.DATABASE_URL); pool = mysql.createPool({ host: u.hostname, port: Number(u.port || 3306), user: decodeURIComponent(u.username), password: decodeURIComponent(u.password), database: u.pathname.slice(1), connectionLimit: 8 }); await purgeInterruptedFixtures(); }); test.afterEach(async () => { await Promise.all([...runtimes].map((value) => value.stop())); runtimes.clear(); await cleanup(); }); test.after(async () => { try { await purgeInterruptedFixtures(); } finally { await pool.end(); } });
test('runtime processes a success on a manual first tick', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); const r = runtime(p); await r.start(); await r.runTickNow(); assert.equal((await state(f)).job.status, 'succeeded'); await r.stop(); });
test('terminal jobs are absent from a second runtime tick', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); const r = runtime(p); await r.start(); await r.runTickNow(); await r.runTickNow(); assert.equal(p.pollCount(f.providerJobId), 1); await r.stop(); });
test('multiple jobs are processed across runtime ticks', async () => { const a = await fixture(); const b = await fixture(); const p = createFakeVideoProvider(); p.plan(a.providerJobId, 'succeeded'); p.plan(b.providerJobId, 'failed'); const r = runtime(p); await r.start(); await r.runTickNow(); assert.equal((await state(a)).job.status, 'succeeded'); assert.equal((await state(b)).job.status, 'failed'); await r.stop(); });
test('two runtimes have one effective MariaDB poll', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); const a = runtime(p, 'runtime-a'), b = runtime(p, 'runtime-b'); await Promise.all([a.start(), b.start()]); await Promise.all([a.runTickNow(), b.runTickNow()]); assert.equal(p.pollCount(f.providerJobId), 1); await Promise.all([a.stop(), b.stop()]); });
test('a runtime does not overlap an in-flight MariaDB tick', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); const original = p.getJobStatus; let release; const gate = new Promise((resolve) => { release = resolve; }); p.getJobStatus = async (providerJobId) => { await gate; return original(providerJobId); }; const r = runtime(p); await r.start(); const first = r.runTickNow(); assert.equal((await r.runTickNow()).action, 'overlap-ignored'); release(); await first; assert.equal((await state(f)).job.status, 'succeeded'); await r.stop(); });
test('stop allows a later runtime to recover an expired lease', async () => { const f = await fixture({ status: 'processing' }); await q("UPDATE app_video_generations SET worker_lease_owner='old', worker_lease_until=DATE_SUB(NOW(), INTERVAL 1 SECOND) WHERE id=?", [f.jobId]); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); const r = runtime(p); await r.start(); await r.runTickNow(); assert.equal((await state(f)).job.status, 'succeeded'); await r.stop(); });
test('temporary provider error does not stop the next runtime tick', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, ['http_500', 'succeeded']); const r = runtime(p); await r.start(); await r.runTickNow(); await q('UPDATE app_video_generations SET next_poll_at=NOW() WHERE id=?', [f.jobId]); await r.runTickNow(); assert.equal((await state(f)).job.status, 'succeeded'); await r.stop(); });
test('expired jobs are released by runtime without provider polling', async () => { const f = await fixture({ expires: 'DATE_SUB(NOW(), INTERVAL 1 MINUTE)' }); const p = createFakeVideoProvider(); const r = runtime(p); await r.start(); await r.runTickNow(); assert.equal((await state(f)).job.status, 'expired'); assert.equal(p.pollCount(f.providerJobId), 0); await r.stop(); });
test('runtime state remains free of job and provider data', async () => { const r = runtime(createFakeVideoProvider()); await r.start(); const s = r.getState(); assert.equal('providerJobId' in s, false); assert.equal('prompt' in s, false); await r.stop(); });
