process.env.NODE_ENV = 'test';
const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { randomUUID } = require('node:crypto');
const mysql = require('mysql2/promise');
require('dotenv').config({ path: path.join(__dirname, '../../../../.env') });
const { createVideoWorkerRepository } = require('../worker/video-worker.repository');
const { createVideoJobProcessingService } = require('../worker/video-job-processing.service');
const { createVideoGenerationWorker } = require('../worker/video-generation.worker');
const { createFakeVideoProvider } = require('../providers/fake-video.provider');

let pool; const ids = new Set(); const config = { leaseMs: 5_000, batchSize: 5, maxPollAttempts: 3, pollBaseDelayMs: 100, pollMaxDelayMs: 400 };
const id = (prefix) => { const value = `${prefix}-${randomUUID()}`; ids.add(value); return value; };
async function q(sql, params) { return pool.query(sql, params); }
async function fixture({ provider = 'fake', status = 'submitted', expires = 'DATE_ADD(NOW(), INTERVAL 1 HOUR)', attempts = 0, units = 1 } = {}) {
  const userId = id('worker-user'), planId = id('worker-plan'), modelKey = id('worker-model').slice(0, 64), jobId = id('worker-job'), reservationId = id('worker-reservation'), providerJobId = id('provider-job'), periodKey = '2099-12';
  await q('INSERT INTO app_users (user_id,name,age,registered_at) VALUES (?,?,20,NOW())', [userId, 'Worker']);
  await q('INSERT INTO app_plans (id,name,features,is_active,created_at,updated_at) VALUES (?,?,JSON_ARRAY(),0,NOW(),NOW())', [planId, 'Worker']);
  await q("INSERT INTO app_video_models (internal_key,provider,provider_model_id,display_name_fa,is_active,supports_text_to_video,supports_image_to_video,allowed_aspect_ratios,allowed_durations,allowed_qualities,max_prompt_length,quota_units,created_at,updated_at) VALUES (?,?,?,'مدل',0,1,0,JSON_ARRAY('16:9'),JSON_ARRAY('4'),JSON_ARRAY('standard'),100,?,NOW(),NOW())", [modelKey, provider, 'model', units]);
  await q('INSERT INTO app_video_usage (user_id,period_key,video_used,video_reserved,updated_at) VALUES (?,?,0,?,NOW())', [userId, periodKey, units]);
  await q(`INSERT INTO app_video_generations (id,user_id,mode,model_key,provider,provider_model_id_snapshot,status,prompt,aspect_ratio,duration,quality,provider_job_id,quota_units,quota_reservation_id,idempotency_hash,payload_hash,expires_at,next_poll_at,poll_attempts,created_at,updated_at) VALUES (?,?,'text-to-video',?,?, 'model',?,'fixture','16:9','4','standard',?,?,?,SHA2(UUID(),256),SHA2(UUID(),256),${expires},NOW(),?,NOW(),NOW())`, [jobId, userId, modelKey, provider, status, providerJobId, units, reservationId, attempts]);
  await q("INSERT INTO app_video_quota_reservations (id,user_id,period_key,generation_id,quota_units,status,created_at,updated_at) VALUES (?,?,?,?,?,'reserved',NOW(),NOW())", [reservationId, userId, periodKey, jobId, units]);
  return { userId, jobId, reservationId, providerJobId, periodKey, units };
}
async function state(f) { const [[job]] = await q('SELECT * FROM app_video_generations WHERE id=?', [f.jobId]); const [[reservation]] = await q('SELECT * FROM app_video_quota_reservations WHERE id=?', [f.reservationId]); const [[usage]] = await q('SELECT * FROM app_video_usage WHERE user_id=? AND period_key=?', [f.userId, f.periodKey]); return { job, reservation, usage }; }
async function cleanup() { for (const value of ids) { await q('DELETE FROM app_video_quota_reservations WHERE id=?', [value]); await q('DELETE FROM app_video_generations WHERE id=?', [value]); await q('DELETE FROM app_video_models WHERE internal_key=?', [value]); await q('DELETE FROM app_video_usage WHERE user_id=?', [value]); await q('DELETE FROM app_plans WHERE id=?', [value]); await q('DELETE FROM app_users WHERE user_id=?', [value]); } ids.clear(); }
function worker(provider, workerId = `worker-${randomUUID().slice(0, 8)}`) { const repository = createVideoWorkerRepository(pool); const service = createVideoJobProcessingService({ repository, providerRegistry: { fake: provider }, config }); return createVideoGenerationWorker({ repository, processingService: service, config, workerId }); }
test.before(async () => { execFileSync(process.execPath, ['scripts/apply-video-generation-migration.js'], { cwd: path.join(__dirname, '../../../..'), stdio: 'inherit' }); const url = new URL(process.env.DATABASE_URL); pool = mysql.createPool({ host: url.hostname, port: Number(url.port || 3306), user: decodeURIComponent(url.username), password: decodeURIComponent(url.password), database: url.pathname.slice(1), connectionLimit: 8 }); });
test.afterEach(cleanup); test.after(async () => { try { await cleanup(); } finally { await pool.end(); } });

test('worker claims and finalizes a success once', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); await worker(p).tick(); const s = await state(f); assert.equal(s.job.status, 'succeeded'); assert.equal(s.reservation.status, 'finalized'); assert.equal(Number(s.usage.video_used), 1); });
test('worker releases failed jobs', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'failed'); await worker(p).tick(); const s = await state(f); assert.equal(s.job.status, 'failed'); assert.equal(s.reservation.status, 'released'); assert.equal(Number(s.usage.video_used), 0); });
test('processing response is scheduled with lease released', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'processing'); await worker(p).tick(); const s = await state(f); assert.equal(s.job.status, 'submitted'); assert.equal(s.job.worker_lease_owner, null); assert.equal(Number(s.job.poll_attempts), 1); });
test('temporary provider network failure is retried', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'network_error'); await worker(p).tick(); const s = await state(f); assert.equal(s.job.status, 'submitted'); assert.equal(s.reservation.status, 'reserved'); });
test('stored timeout expires without polling', async () => { const f = await fixture({ expires: 'DATE_SUB(NOW(), INTERVAL 1 MINUTE)' }); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); await worker(p).tick(); const s = await state(f); assert.equal(s.job.status, 'expired'); assert.equal(p.pollCount(f.providerJobId), 0); });
test('max attempts expires and releases quota', async () => { const f = await fixture({ attempts: 3 }); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); await worker(p).tick(); const s = await state(f); assert.equal(s.job.status, 'expired'); assert.equal(s.job.safe_error_code, 'VIDEO_MAX_POLL_ATTEMPTS_REACHED'); });
test('restart recovery claims an expired old lease', async () => { const f = await fixture({ status: 'processing' }); await q("UPDATE app_video_generations SET worker_lease_owner='old', worker_lease_until=DATE_SUB(NOW(), INTERVAL 1 SECOND) WHERE id=?", [f.jobId]); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); await worker(p, 'new-worker').tick(); assert.equal((await state(f)).job.status, 'succeeded'); });
test('wrong lease owner cannot settle a claimed job', async () => { const f = await fixture(); const repository = createVideoWorkerRepository(pool); const [claimed] = await repository.claimPollableJobs({ workerId: 'owner-a', leaseSeconds: 30 }); await q("UPDATE app_video_generations SET worker_lease_owner='owner-b' WHERE id=?", [f.jobId]); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); const service = createVideoJobProcessingService({ repository, providerRegistry: { fake: p }, config }); assert.equal((await service.processClaimedJob(claimed, { workerId: 'owner-a' })).action, 'ignored-lease-lost'); assert.equal((await state(f)).job.status, 'submitted'); });
test('terminal jobs are never polled again', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); const w = worker(p); await w.tick(); await w.tick(); assert.equal(p.pollCount(f.providerJobId), 1); });
test('duplicate success consumes quota once', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, ['succeeded', 'succeeded']); const w = worker(p); await w.tick(); await w.tick(); const s = await state(f); assert.equal(Number(s.usage.video_used), 1); assert.equal(Number(s.usage.video_reserved), 0); });
test('duplicate failure releases quota once', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, ['failed', 'failed']); const w = worker(p); await w.tick(); await w.tick(); const s = await state(f); assert.equal(Number(s.usage.video_used), 0); assert.equal(Number(s.usage.video_reserved), 0); });
test('two concurrent workers make one effective poll', async () => { const f = await fixture(); const p = createFakeVideoProvider(); p.plan(f.providerJobId, 'succeeded'); await Promise.all([worker(p, 'concurrent-a').tick(), worker(p, 'concurrent-b').tick()]); assert.equal(p.pollCount(f.providerJobId), 1); assert.equal((await state(f)).job.status, 'succeeded'); });
test('one tick handles multiple jobs in its batch', async () => { const one = await fixture(); const two = await fixture(); const p = createFakeVideoProvider(); p.plan(one.providerJobId, 'succeeded'); p.plan(two.providerJobId, 'failed'); const out = await worker(p).tick(); assert.equal(out.processed, 2); assert.equal((await state(one)).job.status, 'succeeded'); assert.equal((await state(two)).job.status, 'failed'); });
test('a temporary error does not block a following job', async () => { const one = await fixture(); const two = await fixture(); const p = createFakeVideoProvider(); p.plan(one.providerJobId, 'http_500'); p.plan(two.providerJobId, 'succeeded'); await worker(p).tick(); assert.equal((await state(one)).job.status, 'submitted'); assert.equal((await state(two)).job.status, 'succeeded'); });
test('final usage is correct across success and failure', async () => { const one = await fixture({ units: 2 }); const two = await fixture({ units: 3 }); const p = createFakeVideoProvider(); p.plan(one.providerJobId, 'succeeded'); p.plan(two.providerJobId, 'failed'); await worker(p).tick(); assert.equal(Number((await state(one)).usage.video_used), 2); assert.equal(Number((await state(two)).usage.video_used), 0); });
test('fixtures are isolated by generated ids', async () => { const f = await fixture(); assert.equal((await state(f)).reservation.status, 'reserved'); });
