'use strict';

const test=require('node:test');const assert=require('node:assert/strict');
const {createVideoGenerationService}=require('../video-generation.service');
const {jobDto}=require('../video-generation.service');
const {VideoPromptCompiler}=require('../../video-prompt-profiles/video-prompt-compiler');
const {VIDEO_PROMPT_PRESETS}=require('../../video-prompt-profiles/video-prompt-presets');
const {createNoaBillingFixture}=require('./noa-billing.fixture');

const preset=VIDEO_PROMPT_PRESETS[0];
const profile={id:preset.id,current_version_id:preset.versionId,profile_key:preset.profileKey,version:1,base_system_prompt:'canonical cinematic base',execution_template:preset.executionTemplate,rules_manifest_json:preset.rulesManifest};
const animationPreset=VIDEO_PROMPT_PRESETS[1];
const animationProfile={id:animationPreset.id,current_version_id:animationPreset.versionId,profile_key:animationPreset.profileKey,version:1,base_system_prompt:'canonical animation base',execution_template:animationPreset.executionTemplate,rules_manifest_json:animationPreset.rulesManifest};
const model={internal_key:'route-model',supports_text_to_video:0,supports_image_to_video:1,supports_negative_prompt:0,supports_audio:0,allowed_aspect_ratios:'["9:16"]',allowed_durations:'["5"]',allowed_qualities:'[]',allowed_resolutions:'["720p"]',max_prompt_length:2000};
const input={mode:'image_to_video',styleKey:'cinematic',mediaId:'media-1',prompt:'شخص آرام لبخند بزند',duration:5,resolution:'720p',aspectRatio:'9:16'};
function fixture({profileValue=profile}={}){let stored;const repository={findIdempotent:async()=>null,getModel:async()=>model,createRoutedWithReservation:async({job,reservationInput})=>{stored={...job,reservationInput};return {...job,status:'queued',noaReservationId:'noa-fixture'};}};const service=createVideoGenerationService({repository,noaBillingService:createNoaBillingFixture(),provider:{},routeResolver:{resolve:async()=>({routeId:'video-i2v',routeVersion:7,providerKey:'bananaai',providerModelId:'grok-imagine-video',internalModelKey:'route-model',routingPolicy:'PRIMARY_ONLY',candidates:[]})},promptProfileRepository:{getCurrentByKey:async()=>profileValue},promptCompiler:new VideoPromptCompiler(),isFeatureEnabled:()=>true});return{service,getStored:()=>stored};}

test('I2V submit compiles and snapshots profile/version/hash before persistence',async()=>{const value=fixture();const result=await value.service.submit({userId:'user-1',idempotencyKey:'fixture-key-123',input});const job=value.getStored();assert.equal(result.status,'queued');assert.equal(job.promptProfileId,preset.id);assert.equal(job.promptProfileVersionId,preset.versionId);assert.equal(job.promptProfileKey,'cinematic');assert.equal(job.promptProfileVersion,1);assert.equal(job.promptCompilerVersion,'3');assert.equal(job.userPrompt,input.prompt);assert.match(job.compiledPrompt,/\[\[SYSTEM PROMPT\]\]\ncanonical cinematic base/);assert.match(job.compiledPrompt,/\[\[NON-NEGOTIABLE RULES\]\]/);assert.ok(job.compiledPrompt.length<=2000);assert.match(job.compiledPromptHash,/^[a-f0-9]{64}$/);});
test('route and provider selection stay outside the compiler snapshot',async()=>{const value=fixture();await value.service.submit({userId:'user-1',idempotencyKey:'fixture-key-456',input});const job=value.getStored();assert.equal(job.provider,'bananaai');assert.equal(job.providerModelId,'grok-imagine-video');assert.equal(job.compiledPrompt.includes('bananaai'),false);assert.equal(job.compiledPrompt.includes('grok-imagine-video'),false);});
test('cinematic and animation use different TXT systems but the same Grok model',async()=>{const cinematic=fixture();await cinematic.service.submit({userId:'user-1',idempotencyKey:'fixture-key-style-c',input});const animation=fixture({profileValue:animationProfile});await animation.service.submit({userId:'user-1',idempotencyKey:'fixture-key-style-a',input:{...input,styleKey:'animation'}});const cinematicJob=cinematic.getStored();const animationJob=animation.getStored();assert.equal(cinematicJob.providerModelId,'grok-imagine-video');assert.equal(animationJob.providerModelId,'grok-imagine-video');assert.match(cinematicJob.compiledPrompt,/canonical cinematic base/);assert.match(animationJob.compiledPrompt,/canonical animation base/);assert.notEqual(cinematicJob.compiledPrompt,animationJob.compiledPrompt);});
test('private, inactive or unknown style fails before reservation persistence',async()=>{const value=fixture({profileValue:null});await assert.rejects(value.service.submit({userId:'user-1',idempotencyKey:'fixture-key-789',input}),{code:'VIDEO_PROMPT_PROFILE_UNAVAILABLE'});assert.equal(value.getStored(),undefined);});
test('styleKey is mandatory for routed image-to-video',async()=>{const value=fixture();await assert.rejects(value.service.submit({userId:'user-1',idempotencyKey:'fixture-key-000',input:{...input,styleKey:undefined}}),{code:'VIDEO_PROMPT_PROFILE_REQUIRED'});});
test('I2V rejects any resolved route that is not BananaAI Grok',async()=>{let reserved=false;const repository={findIdempotent:async()=>null,getModel:async()=>model,createRoutedWithReservation:async()=>{reserved=true;throw new Error('must not persist');}};const service=createVideoGenerationService({repository,noaBillingService:createNoaBillingFixture(),provider:{},routeResolver:{resolve:async()=>({routeId:'video-i2v',routeVersion:8,providerKey:'bananaai',providerModelId:'seedance-2',internalModelKey:'route-model',routingPolicy:'PRIMARY_ONLY',candidates:[]})},promptProfileRepository:{getCurrentByKey:async()=>profile},promptCompiler:new VideoPromptCompiler(),isFeatureEnabled:()=>true});await assert.rejects(service.submit({userId:'user-1',idempotencyKey:'fixture-key-route',input}),{code:'VIDEO_GENERATION_MODEL_UNAVAILABLE'});assert.equal(reserved,false);});
test('raw user prompt remains separate and is not replaced in public job history',async()=>{const value=fixture();await value.service.submit({userId:'user-1',idempotencyKey:'fixture-key-111',input});const job=value.getStored();assert.equal(job.prompt,input.prompt);assert.equal(job.userPrompt,input.prompt);assert.notEqual(job.compiledPrompt,input.prompt);});
test('public job DTO hides provider, model and all compiled prompt fields',()=>{const dto=jobDto({id:'job-1',mode:'image-to-video',model_key:'secret-model',provider:'bananaai',provider_job_id:'task-secret',status:'queued',prompt:'user prompt',compiled_prompt:'secret compiled',base_system_prompt:'secret system',aspect_ratio:'9:16',duration:'5',created_at:new Date(),updated_at:new Date()});const serialized=JSON.stringify(dto);for(const forbidden of ['secret-model','bananaai','task-secret','secret compiled','secret system'])assert.equal(serialized.includes(forbidden),false);assert.equal(dto.prompt,'user prompt');});
