const test = require('node:test');
const assert = require('node:assert/strict');
const { createConfiguredVideoWorkerRuntime, createVideoWorkerProviderRegistry } = require('../worker/video-worker.bootstrap');
const { createHealthService } = require('../../health/health.service');
const { runDedicatedWorker } = require('../../../../scripts/run-video-worker');
const { createNoaBillingFixture } = require('./noa-billing.fixture');

const env = (more = {}) => ({ NODE_ENV: 'test', VIDEO_WORKER_ENABLED: 'true', VIDEO_WORKER_PROCESS_MODE: 'embedded', VIDEO_WORKER_INTERVAL_MS: '1000', VIDEO_WORKER_LEASE_MS: '1000', VIDEO_WORKER_BATCH_SIZE: '1', VIDEO_JOB_TIMEOUT_MINUTES: '30', VIDEO_MAX_POLL_ATTEMPTS: '2', VIDEO_POLL_BASE_DELAY_MS: '100', VIDEO_POLL_MAX_DELAY_MS: '200', VIDEO_WORKER_SHUTDOWN_TIMEOUT_MS: '100', ...more });
const db = { query: async () => [{ affectedRows: 0 }], getConnection: async () => ({ beginTransaction: async () => {}, commit: async () => {}, rollback: async () => {}, release: () => {}, query: async () => [[]] }) };

test('test registry has fake providers and makes no HTTP request at creation', () => { let calls = 0; const registry = createVideoWorkerProviderRegistry({ env: env(), httpClient: { get: () => { calls += 1; } } }); assert.equal(registry.fake.kind, 'fake'); assert.equal(calls, 0); });
test('embedded runtime remains disabled when flag is false', async () => { const runtime = createConfiguredVideoWorkerRuntime({ db, httpClient: {}, noaBillingService:createNoaBillingFixture(), env: env({ VIDEO_WORKER_ENABLED: 'false' }) }); assert.equal((await runtime.start()).action, 'disabled'); });
test('embedded runtime starts only after construction and can stop', async () => { const runtime = createConfiguredVideoWorkerRuntime({ db, httpClient: {}, noaBillingService:createNoaBillingFixture(), env: env() }); assert.equal((await runtime.start()).action, 'started'); assert.equal(runtime.isStarted(), true); await runtime.stop(); assert.equal(runtime.isStarted(), false); });
test('dedicated mode does not start in embedded runtime', async () => { const runtime = createConfiguredVideoWorkerRuntime({ db, httpClient: {}, noaBillingService:createNoaBillingFixture(), env: env({ VIDEO_WORKER_PROCESS_MODE: 'dedicated' }) }); assert.equal((await runtime.start()).action, 'disabled'); });
test('invalid startup config has a clear error', () => { assert.throws(() => createConfiguredVideoWorkerRuntime({ db, httpClient: {}, noaBillingService:createNoaBillingFixture(), env: env({ VIDEO_WORKER_PROCESS_MODE: 'unknown' }) }), /PROCESS_MODE/); });
test('health state intentionally exposes only compact worker data', () => { const health = createHealthService({ defaultModel: 'x', metisBaseUrl: 'x', videoWorkerState: () => ({ enabled: true, mode: 'embedded', state: 'idle' }) }); assert.deepEqual(health.getStatus().videoWorker, { enabled: true, mode: 'embedded', state: 'idle' }); });
test('server import has no startup side effect', () => { const server = require('../../../server'); assert.equal(typeof server.startServer, 'function'); });
test('dedicated worker disabled mode starts no worker and closes database', async () => { let initialized = 0; let closed = 0; const runtime = { start: async () => ({ action: 'disabled' }), stop: async () => {} }; const result = await runDedicatedWorker({ env: env({ VIDEO_WORKER_ENABLED: 'false', VIDEO_WORKER_PROCESS_MODE: 'disabled' }), installSignalHandlers: false, repositoriesFactory: () => ({ db: { init: async () => { initialized += 1; }, close: async () => { closed += 1; } } }), noaBillingServiceFactory:()=>createNoaBillingFixture(), runtimeFactory: () => runtime }); await result.shutdown(); assert.equal(initialized, 1); assert.equal(closed, 1); });
test('dedicated role is passed to its runtime factory', async () => { let role; const result = await runDedicatedWorker({ env: env({ VIDEO_WORKER_PROCESS_MODE: 'dedicated' }), installSignalHandlers: false, repositoriesFactory: () => ({ db: { init: async () => {}, close: async () => {} } }), noaBillingServiceFactory:()=>createNoaBillingFixture(), runtimeFactory: (input) => { role = input.role; return { start: async () => ({ action: 'started' }), stop: async () => {} }; } }); assert.equal(role, 'dedicated'); await result.shutdown(); });
test('provider registry uses metis adapter outside tests without a startup health call', () => { let calls = 0; const registry = createVideoWorkerProviderRegistry({ env: env({ NODE_ENV: 'production' }), httpClient: { get: () => { calls += 1; } } }); assert.ok(registry.metis); assert.equal(calls, 0); });
