const test = require('node:test');
const assert = require('node:assert/strict');
const { createVideoGenerationWorker } = require('../worker/video-generation.worker');
const config = { leaseMs: 1000, batchSize: 2 };
function makeWorker({ jobs = [], process = async () => ({ action: 'ok' }) } = {}) { const calls = []; const repository = { recoverExpiredLeases: async () => calls.push('recover'), claimExpiredJobs: async (args) => { calls.push({ ...args, expired: true }); return []; }, claimPollableJobs: async (args) => { calls.push(args); return jobs; } }; return { calls, worker: createVideoGenerationWorker({ repository, processingService: { processClaimedJob: process }, config, workerId: 'worker-test' }) }; }
test('manual tick with no jobs performs no work', async () => { const f = makeWorker(); const out = await f.worker.tick(); assert.equal(out.processed, 0); assert.equal(f.worker.isRunning(), false); });
test('tick processes a limited batch and forwards its owner', async () => { const seen = []; const f = makeWorker({ jobs: [{ id: '1' }, { id: '2' }], process: async (job, input) => { seen.push([job.id, input.workerId]); return { action: 'ok' }; } }); const out = await f.worker.tick(); assert.equal(out.processed, 2); assert.deepEqual(seen, [['1', 'worker-test'], ['2', 'worker-test']]); assert.equal(f.calls[2].limit, 2); });
test('one job error does not stop the batch', async () => { let calls = 0; const f = makeWorker({ jobs: [{ id: 'bad' }, { id: 'good' }], process: async () => { calls += 1; if (calls === 1) throw new Error('bad'); return { action: 'ok' }; } }); const out = await f.worker.tick(); assert.equal(out.results[0].action, 'error'); assert.equal(out.results[1].action, 'ok'); });
test('overlapping tick is a safe no-op', async () => { let release; const gate = new Promise((resolve) => { release = resolve; }); const f = makeWorker({ jobs: [{ id: '1' }], process: async () => gate }); const first = f.worker.tick(); assert.equal((await f.worker.tick()).action, 'overlap-ignored'); release(); await first; });
test('stop disables future manual ticks and creates no timer', async () => { const f = makeWorker(); f.worker.stop(); assert.equal((await f.worker.tick()).action, 'stopped'); assert.equal(typeof f.worker.workerId, 'string'); assert.match(f.worker.workerId, /^worker-test$/); });
