const test = require('node:test');
const assert = require('node:assert/strict');
const { createVideoWorkerRuntime } = require('../worker/video-worker.runtime');
const { loadVideoWorkerConfig } = require('../worker/video-worker.config');

function fakeTimers() { let id = 0; const tasks = new Map(); return { tasks, setTimeout(fn, delay) { const key = ++id; tasks.set(key, { fn, delay }); return key; }, clearTimeout(key) { tasks.delete(key); }, async runNext() { const [key, task] = tasks.entries().next().value || []; if (!task) return; tasks.delete(key); await task.fn(); } }; }
function config(overrides = {}) { return loadVideoWorkerConfig({ VIDEO_WORKER_ENABLED: 'true', VIDEO_WORKER_PROCESS_MODE: 'embedded', VIDEO_WORKER_INTERVAL_MS: '1000', VIDEO_WORKER_LEASE_MS: '1000', VIDEO_WORKER_SHUTDOWN_TIMEOUT_MS: '100', VIDEO_WORKER_BATCH_SIZE: '1', VIDEO_JOB_TIMEOUT_MINUTES: '30', VIDEO_MAX_POLL_ATTEMPTS: '2', VIDEO_POLL_BASE_DELAY_MS: '100', VIDEO_POLL_MAX_DELAY_MS: '200', ...overrides }); }
function subject({ result = { processed: 0 }, tick, workerId = 'worker-secret-id', options = {} } = {}) { const timers = fakeTimers(); let calls = 0; const runtime = createVideoWorkerRuntime({ config: config(options.env), role: options.role || 'embedded', timers, clock: () => new Date('2030-01-01T00:00:00Z'), createWorker: () => ({ workerId, stop: () => { calls += 100; }, tick: tick || (async () => { calls += 1; return result; }) }), workerDependencies: {} }); return { runtime, timers, calls: () => calls }; }

test('disabled start creates no worker timer', async () => { const s = subject({ options: { env: { VIDEO_WORKER_ENABLED: 'false' } } }); assert.equal((await s.runtime.start()).action, 'disabled'); assert.equal(s.timers.tasks.size, 0); });
test('start is idempotent and schedules delayed tick', async () => { const s = subject(); assert.equal((await s.runtime.start()).action, 'started'); assert.equal((await s.runtime.start()).action, 'already-started'); assert.equal(s.timers.tasks.size, 1); });
test('stop before start and after start is safe', async () => { const s = subject(); assert.equal((await s.runtime.stop()).action, 'already-stopped'); await s.runtime.start(); assert.equal((await s.runtime.stop()).action, 'stopped'); assert.equal(s.timers.tasks.size, 0); });
test('manual tick calls core worker', async () => { const s = subject({ result: { processed: 2 } }); await s.runtime.start(); const result = await s.runtime.runTickNow(); assert.equal(result.processed, 2); assert.equal(s.runtime.getState().lastTickProcessedCount, 2); });
test('run immediately starts a tick without a timer', async () => { const s = subject({ options: { env: { VIDEO_WORKER_RUN_IMMEDIATELY: 'true' } } }); await s.runtime.start(); await new Promise(setImmediate); assert.equal(s.calls(), 1); });
test('run immediately false waits for the scheduler', async () => { const s = subject(); await s.runtime.start(); assert.equal(s.calls(), 0); await s.timers.runNext(); assert.equal(s.calls(), 1); });
test('runtime blocks overlapping manual ticks', async () => { let release; const gate = new Promise((resolve) => { release = resolve; }); const s = subject({ tick: async () => gate }); await s.runtime.start(); const one = s.runtime.runTickNow(); assert.equal((await s.runtime.runTickNow()).action, 'overlap-ignored'); release({ processed: 0 }); await one; });
test('a tick error is safe and another tick is scheduled', async () => { let first = true; const s = subject({ tick: async () => { if (first) { first = false; const e = new Error('secret'); e.code = 'SAFE_CODE'; throw e; } return { processed: 1 }; } }); await s.runtime.start(); const result = await s.runtime.runTickNow(); assert.equal(result.errorCode, 'SAFE_CODE'); assert.equal(s.runtime.getState().lastSafeErrorCode, 'SAFE_CODE'); assert.equal(s.timers.tasks.size, 1); });
test('scheduled ticks do not overlap and schedule the next tick', async () => { const s = subject(); await s.runtime.start(); await s.timers.runNext(); assert.equal(s.timers.tasks.size, 1); assert.equal(s.runtime.isTickRunning(), false); });
test('stop prevents pending scheduled tick', async () => { const s = subject(); await s.runtime.start(); await s.runtime.stop(); await s.timers.runNext(); assert.equal(s.calls(), 100); });
test('state transitions are operational and safe', async () => { const s = subject(); await s.runtime.start(); const state = s.runtime.getState(); assert.equal(state.state, 'idle'); assert.equal(state.workerOwnerShort, 'worker-secre'); assert.equal('providerJobId' in state, false); });
test('mode mismatch remains disabled', async () => { const s = subject({ options: { env: { VIDEO_WORKER_PROCESS_MODE: 'dedicated' } } }); assert.equal((await s.runtime.start()).action, 'disabled'); });
test('invalid config is rejected', () => { assert.throws(() => config({ VIDEO_WORKER_INTERVAL_MS: '-1' }), /INTERVAL/); assert.throws(() => config({ VIDEO_WORKER_PROCESS_MODE: 'bad' }), /PROCESS_MODE/); });
test('config is immutable', () => { assert.equal(Object.isFrozen(config()), true); });
test('no import side effect', () => { delete require.cache[require.resolve('../worker/video-worker.runtime')]; const runtime = require('../worker/video-worker.runtime'); assert.equal(typeof runtime.createVideoWorkerRuntime, 'function'); });
test('shutdown timeout does not create a new tick', async () => { let release; const gate = new Promise((resolve) => { release = resolve; }); const s = subject({ tick: async () => gate }); await s.runtime.start(); void s.runtime.runTickNow(); const stopping = s.runtime.stop(); await s.timers.runNext(); await stopping; assert.equal(s.runtime.getState().state, 'stopped'); release({ processed: 0 }); });
test('owner id is shortened in state', async () => { const s = subject({ workerId: '12345678901234567890' }); await s.runtime.start(); assert.equal(s.runtime.getState().workerOwnerShort.length, 12); });
