const test = require('node:test');
const assert = require('node:assert/strict');
const { parseRange } = require('../video-content.controller');
const { createVideoContentController } = require('../video-content.controller');
const { createVideoContentAuthController } = require('../video-content-auth.controller');
const jwt = require('jsonwebtoken');
const { Writable } = require('stream');
const { once } = require('events');
class Response extends Writable { constructor() { super(); this.headers = {}; this.statusCode = 200; this.body = Buffer.alloc(0); } _write(chunk, _enc, done) { this.body = Buffer.concat([this.body, chunk]); done(); } setHeader(k, v) { this.headers[k.toLowerCase()] = String(v); } status(n) { this.statusCode = n; return this; } json(value) { this.jsonBody = value; return this.end(); } }
const bytes = Buffer.from('000000186674797069736f6d0000020069736f6d69736f6d', 'hex');
const succeeded = { id: 'generation-1', status: 'succeeded', result_storage_key: 'results/a/output.mp4', result_mime_type: 'video/mp4', result_original_filename: 'unsafe\r\nname.mp4' };
function makeController({ job = succeeded, adminJob = null } = {}) { const storage = { stat: async () => ({ size: bytes.length }), openReadStream: (_key, range = {}) => require('stream').Readable.from([bytes.subarray(range.start || 0, range.end === undefined ? bytes.length : range.end + 1)]) }; const service = { get: async () => job, getForAdmin: async () => adminJob || job }; return createVideoContentController({ service, storage }); }
async function invoke(controller, req, res) { await controller(req, res); if (!res.writableEnded) await once(res, 'finish'); }
test('content range parsing supports closed, open and suffix ranges', () => { assert.deepEqual(parseRange('bytes=0-99', 1000), { start: 0, end: 99 }); assert.deepEqual(parseRange('bytes=100-', 1000), { start: 100, end: 999 }); assert.deepEqual(parseRange('bytes=-100', 1000), { start: 900, end: 999 }); });
test('content range parsing rejects invalid and reversed ranges', () => { assert.equal(parseRange('bytes=1000-1001', 1000), 'invalid'); assert.equal(parseRange('bytes=100-99', 1000), 'invalid'); assert.equal(parseRange('wat', 1000), 'invalid'); });
test('owner receives a streamed complete response without a storage-key leak', async () => { const res = new Response(); await invoke(makeController(), { params: { generationId: 'generation-1' }, user: { id: 'owner' }, headers: {}, query: {}, method: 'GET' }, res); assert.equal(res.statusCode, 200); assert.equal(res.body.equals(bytes), true); assert.equal(res.headers['content-length'], String(bytes.length)); assert.equal(res.headers['content-disposition'].includes('\r'), false); });
test('range, download, HEAD and invalid range have safe HTTP semantics', async () => { const controller = makeController(); const range = new Response(); await invoke(controller, { params: {}, user: { id: 'owner' }, headers: { range: 'bytes=0-9' }, query: { download: '1' }, method: 'GET' }, range); assert.equal(range.statusCode, 206); assert.equal(range.body.length, 10); assert.match(range.headers['content-range'], /^bytes 0-9\//); assert.match(range.headers['content-disposition'], /^attachment/); const head = new Response(); await invoke(controller, { params: {}, user: { id: 'owner' }, headers: {}, query: {}, method: 'HEAD' }, head); assert.equal(head.body.length, 0); const invalid = new Response(); await invoke(controller, { params: {}, user: { id: 'owner' }, headers: { range: 'bytes=999-' }, query: {}, method: 'GET' }, invalid); assert.equal(invalid.statusCode, 416); });
test('other user, non-ready and missing-file states are denied safely', async () => { const missing = new Response(); await makeController({ job: null })({ params: {}, user: { id: 'other' }, headers: {}, query: {}, method: 'GET' }, missing); assert.equal(missing.statusCode, 404); const pending = new Response(); await makeController({ job: { ...succeeded, status: 'processing' } })({ params: {}, user: { id: 'owner' }, headers: {}, query: {}, method: 'GET' }, pending); assert.equal(pending.statusCode, 409); const absent = new Response(); const storage = { stat: async () => { throw new Error('missing'); } }; const controller = createVideoContentController({ service: { get: async () => succeeded, getForAdmin: async () => succeeded }, storage }); await controller({ params: {}, user: { id: 'owner' }, headers: {}, query: {}, method: 'GET' }, absent); assert.equal(absent.statusCode, 404); });
test('an authenticated admin can read through the admin-only service path', async () => { const res = new Response(); await invoke(makeController({ job: null, adminJob: succeeded }), { params: {}, videoAdmin: { role: 'admin' }, headers: {}, query: {}, method: 'GET' }, res); assert.equal(res.statusCode, 200); assert.equal(res.body.equals(bytes), true); });
test('short-lived, job-scoped content cookie enables native media requests without a URL token', async () => { const secret = 'test-secret'; const cookies = []; const auth = createVideoContentAuthController({ service: { get: async () => ({ id: 'generation-1', status: 'succeeded', result: { contentUrl: '/api/video-generations/generation-1/content' } }) }, jwtSecret: secret }); const authRes = { cookie: (...args) => cookies.push(args), json: (body) => { authRes.body = body; return authRes; } }; await auth({ user: { id: 'owner' }, params: { generationId: 'generation-1' } }, authRes); assert.equal(authRes.body.contentUrl.includes('token'), false); assert.equal(cookies[0][1].includes('generation-1'), false); assert.equal(cookies[0][2].httpOnly, true); assert.equal(cookies[0][2].sameSite, 'strict'); assert.equal(cookies[0][2].maxAge, 300000); assert.equal(cookies[0][2].path, '/api/video-generations/generation-1/content'); const token = cookies[0][1]; const res = new Response(); const controller = createVideoContentController({ service: { get: async () => succeeded, getForAdmin: async () => succeeded }, storage: { stat: async () => ({ size: bytes.length }), openReadStream: () => require('stream').Readable.from([bytes]) }, jwtSecret: secret }); await invoke(controller, { params: { generationId: 'generation-1' }, cookies: { danao_video_content: token }, headers: {}, query: {}, method: 'GET' }, res); assert.equal(res.statusCode, 200); const payload = jwt.verify(token, secret); assert.equal(payload.purpose, 'video-content'); assert.equal(payload.generationId, 'generation-1'); });
test('content authentication does not issue a cookie until a result exists', async () => { const cookies = []; const auth = createVideoContentAuthController({ service: { get: async () => ({ id: 'generation-1', status: 'processing', result: null }) }, jwtSecret: 'test-secret' }); const res = { statusCode: 200, status(code) { this.statusCode = code; return this; }, cookie: (...args) => cookies.push(args), json(body) { this.body = body; return this; } }; await auth({ user: { id: 'owner' }, params: { generationId: 'generation-1' } }, res); assert.equal(res.statusCode, 409); assert.equal(res.body.error, 'VIDEO_RESULT_NOT_READY'); assert.equal(cookies.length, 0); });
