const test = require('node:test');
const assert = require('node:assert/strict');
const { createVideoJobProcessingService } = require('../worker/video-job-processing.service');
const { loadVideoWorkerConfig, calculatePollDelay } = require('../worker/video-worker.config');

const now = new Date('2030-01-01T00:00:00.000Z');
const config = loadVideoWorkerConfig({ VIDEO_WORKER_ENABLED: 'false', VIDEO_WORKER_BATCH_SIZE: '2', VIDEO_WORKER_LEASE_MS: '1000', VIDEO_JOB_TIMEOUT_MINUTES: '30', VIDEO_MAX_POLL_ATTEMPTS: '3', VIDEO_POLL_BASE_DELAY_MS: '100', VIDEO_POLL_MAX_DELAY_MS: '400' });
function job(overrides = {}) { return { id: 'generation-1', provider: 'fake', provider_job_id: 'provider-1', status: 'submitted', worker_lease_owner: 'worker-1', poll_attempts: 1, expires_at: new Date(now.getTime() + 60_000), ...overrides }; }
function fixture({ response = { status: 'processing' }, error = null, extend = true, registry = true } = {}) {
  const calls = []; const provider = { getJobStatus: async () => { if (error) throw error; return response; }, normalizeStatus: (value) => value?.status || null, sanitizeError: () => 'پیام امن' , submitTextToVideo: async () => {}, submitImageToVideo: async () => {} };
  const repository = {};
  for (const name of ['extendJobLease', 'scheduleNextPoll', 'markJobStoring', 'failAndReleaseJob', 'expireAndReleaseJob', 'releaseJobLease']) repository[name] = async (args) => { calls.push([name, args]); return name === 'extendJobLease' ? extend : true; };
  return { calls, provider, service: createVideoJobProcessingService({ repository, providerRegistry: registry ? { fake: provider } : {}, config, clock: () => now }) };
}
const call = (calls, name) => calls.find(([key]) => key === name)?.[1];

for (const status of ['queued', 'processing']) test(`${status} schedules a later poll`, async () => { const f = fixture({ response: { status } }); assert.equal((await f.service.processClaimedJob(job(), { workerId: 'worker-1' })).action, 'scheduled'); assert.equal(call(f.calls, 'scheduleNextPoll').nextPollAt.getTime(), now.getTime() + 100); });
test('completed transitions only to storing until a result is safely stored', async () => { const f = fixture({ response: { status: 'storing' } }); assert.equal((await f.service.processClaimedJob(job(), { workerId: 'worker-1' })).action, 'storing-awaiting-storage'); assert.equal(call(f.calls, 'markJobStoring').workerId, 'worker-1'); assert.equal(f.calls.some(([name]) => name === 'finalizeSuccessfulJob'), false); });
for (const status of ['failed', 'cancelled']) test(`${status} releases reservation`, async () => { const f = fixture({ response: { status } }); await f.service.processClaimedJob(job(), { workerId: 'worker-1' }); assert.equal(call(f.calls, 'failAndReleaseJob').errorCode, status === 'failed' ? 'VIDEO_PROVIDER_FAILED' : 'VIDEO_PROVIDER_CANCELLED'); });
for (const [name, error] of [['network error', Object.assign(new Error(), { code: 'ECONNRESET' })], ['timeout error', Object.assign(new Error(), { code: 'ETIMEDOUT' })], ['429', { response: { status: 429 } }], ['500', { response: { status: 500 } }]]) test(`${name} is retried`, async () => { const f = fixture({ error }); const result = await f.service.processClaimedJob(job(), { workerId: 'worker-1' }); assert.equal(result.action, 'scheduled'); assert.ok(call(f.calls, 'scheduleNextPoll')); });
test('malformed and unknown responses are retried without persisting raw data', async () => { const malformed = fixture({ response: { malformed: true } }); const unknown = fixture({ response: { status: 'mystery' } }); const one = await malformed.service.processClaimedJob(job(), { workerId: 'worker-1' }); const two = await unknown.service.processClaimedJob(job(), { workerId: 'worker-1' }); assert.equal(one.errorCode, 'VIDEO_PROVIDER_MALFORMED_RESPONSE'); assert.equal(two.errorCode, 'VIDEO_PROVIDER_UNKNOWN_STATUS'); assert.equal(JSON.stringify(malformed.calls).includes('malformed'), false); });
test('max attempts expires before another provider poll', async () => { const f = fixture(); const result = await f.service.processClaimedJob(job({ poll_attempts: 4 }), { workerId: 'worker-1' }); assert.equal(result.errorCode, 'VIDEO_MAX_POLL_ATTEMPTS_REACHED'); assert.equal(f.calls.some(([name]) => name === 'expireAndReleaseJob'), true); assert.equal(f.calls.some(([name]) => name === 'extendJobLease'), false); });
test('stored job timeout expires without a provider poll', async () => { const f = fixture(); const result = await f.service.processClaimedJob(job({ expires_at: new Date(now.getTime() - 1) }), { workerId: 'worker-1' }); assert.equal(result.errorCode, 'VIDEO_JOB_TIMEOUT'); assert.equal(f.calls.some(([name]) => name === 'extendJobLease'), false); });
test('terminal jobs, wrong owner, and lost lease are ignored', async () => { const terminal = fixture(); const mismatch = fixture(); const lost = fixture({ extend: false }); assert.equal((await terminal.service.processClaimedJob(job({ status: 'succeeded' }), { workerId: 'worker-1' })).action, 'ignored-terminal'); assert.equal((await mismatch.service.processClaimedJob(job(), { workerId: 'other' })).action, 'ignored-lease-mismatch'); assert.equal((await lost.service.processClaimedJob(job(), { workerId: 'worker-1' })).action, 'ignored-lease-lost'); });
test('permanent errors use provider sanitized text only', async () => { const f = fixture({ error: { response: { status: 401 }, message: 'secret-token' } }); await f.service.processClaimedJob(job(), { workerId: 'worker-1' }); const args = call(f.calls, 'failAndReleaseJob'); assert.equal(args.errorMessage, 'پیام امن'); assert.equal(JSON.stringify(args).includes('secret-token'), false); });
test('missing provider fails safely', async () => { const f = fixture({ registry: false }); const result = await f.service.processClaimedJob(job(), { workerId: 'worker-1' }); assert.equal(result.errorCode, 'VIDEO_PROVIDER_NOT_FOUND'); assert.ok(call(f.calls, 'failAndReleaseJob')); });
test('fake provider cannot be selected in production', async () => { const previous = process.env.NODE_ENV; process.env.NODE_ENV = 'production'; try { const f = fixture(); f.provider.kind = 'fake'; const result = await f.service.processClaimedJob(job(), { workerId: 'worker-1' }); assert.equal(result.errorCode, 'VIDEO_FAKE_PROVIDER_FORBIDDEN'); } finally { if (previous === undefined) delete process.env.NODE_ENV; else process.env.NODE_ENV = previous; } });
test('backoff starts at base and caps without overflow', () => { assert.equal(calculatePollDelay(0, config), 100); assert.equal(calculatePollDelay(2, config), 400); assert.equal(calculatePollDelay(Number.MAX_SAFE_INTEGER, config), 400); });
test('config rejects invalid worker values', () => { assert.throws(() => loadVideoWorkerConfig({ VIDEO_WORKER_BATCH_SIZE: '-1' }), /BATCH_SIZE/); assert.throws(() => loadVideoWorkerConfig({ VIDEO_POLL_BASE_DELAY_MS: '500', VIDEO_POLL_MAX_DELAY_MS: '10' }), /MAX_DELAY/); });
