'use strict';

const test=require('node:test');const assert=require('node:assert/strict');const http=require('node:http');const express=require('express');const {createVideoPromptProfilePublicRouter,createVideoPromptProfileAdminRouter}=require('../../video-prompt-profiles/video-prompt-profile.routes');const {VIDEO_PROMPT_PRESETS}=require('../../video-prompt-profiles/video-prompt-presets');
let server;let origin;const preset=VIDEO_PROMPT_PRESETS[0];
test.before(async()=>{const publicRepository={listPublic:async()=>[{id:preset.id,profileKey:'cinematic',displayName:'واقعی و سینمایی',publicDescription:'عمومی',visualKey:'cinematic-frame',displayOrder:10,currentVersion:1}]};const row={id:preset.id,profile_key:'cinematic',display_name:'واقعی و سینمایی',public_description:'عمومی',visual_key:'cinematic-frame',is_active:1,is_public:1,display_order:10,current_version_id:preset.versionId,version:1,profile_metadata_version:1,prompt_version:1,base_system_prompt:'canonical base',execution_template:preset.executionTemplate,rules_manifest_json:preset.rulesManifest,checksum:'a'.repeat(64),updated_at:new Date()};const db={query:async(sql)=>{if(sql.includes('FROM app_video_prompt_profiles p LEFT JOIN'))return[[row]];if(sql.includes('app_video_prompt_profile_audit_logs'))return[[]];return[[]];}};const requireAdminAuth=(req,res,next)=>{if(req.get('x-test-admin')!=='yes')return res.status(401).json({error:'ADMIN_AUTH_REQUIRED'});req.admin={username:'fixture'};next();};const app=express();app.use(express.json());app.use('/api/video-generations/prompt-profiles',createVideoPromptProfilePublicRouter({repository:publicRepository}));app.use('/api/admin/video-prompt-profiles',createVideoPromptProfileAdminRouter({db,requireAdminAuth}));server=http.createServer(app);await new Promise((resolve)=>server.listen(0,'127.0.0.1',resolve));origin=`http://127.0.0.1:${server.address().port}`;});
test.after(async()=>new Promise((resolve)=>server.close(resolve)));
test('public profile API returns only safe metadata',async()=>{const response=await fetch(`${origin}/api/video-generations/prompt-profiles`);const body=await response.json();assert.equal(response.status,200);assert.equal(body.items[0].profileKey,'cinematic');const serialized=JSON.stringify(body);for(const forbidden of ['baseSystemPrompt','executionTemplate','compiledPrompt','rulesManifest'])assert.equal(serialized.includes(forbidden),false);});
test('Admin profile API requires authorization',async()=>assert.equal((await fetch(`${origin}/api/admin/video-prompt-profiles`)).status,401));
test('Admin compile preview is local and returns version/hash without secrets',async()=>{const response=await fetch(`${origin}/api/admin/video-prompt-profiles/cinematic/compile-preview`,{method:'POST',headers:{'x-test-admin':'yes','Content-Type':'application/json'},body:JSON.stringify({userPrompt:'حرکت آرام',settings:{duration:5,resolution:'720p',aspectRatio:'9:16'}})});const body=await response.json();assert.equal(response.status,200);assert.equal(body.profileKey,'cinematic');assert.match(body.compiledPromptHash,/^[a-f0-9]{64}$/);assert.equal(JSON.stringify(body).includes('apiKey'),false);});
test('Admin writes require reason and optimistic version before DB mutation',async()=>{const response=await fetch(`${origin}/api/admin/video-prompt-profiles/cinematic`,{method:'PATCH',headers:{'x-test-admin':'yes','Content-Type':'application/json'},body:'{}'});assert.equal(response.status,400);assert.equal((await response.json()).error,'VIDEO_PROMPT_PROFILE_REASON_REQUIRED');});

