const { randomUUID } = require('crypto'); const { fail } = require('../video-generation.errors');
function createVideoQuotaService({ db, plansRepository }) {
  const periodKey = () => new Date().toISOString().slice(0, 10);
  return {
    reserve: async ({ userId, units, generationId }) => { const plan = await (plansRepository.getVideoPlanForUser ? plansRepository.getVideoPlanForUser(userId) : plansRepository.getPlanForUser(userId)); if (!plan) throw fail('VIDEO_SUBSCRIPTION_REQUIRED', 'اشتراک فعال برای ساخت ویدیو لازم است.', 403); const limit = Number(plan.videoLimit); if (!Number.isInteger(limit) || limit < 0) throw fail('VIDEO_QUOTA_NOT_CONFIGURED', 'سهمیه ساخت ویدیوی این دوره کافی نیست.', 409); const c = await db.getConnection(); try { await c.beginTransaction(); const key=periodKey(); await c.query('INSERT INTO app_video_usage (user_id,period_key,updated_at) VALUES (?,?,NOW()) ON DUPLICATE KEY UPDATE updated_at=updated_at',[userId,key]); const [usage] = await c.query('SELECT * FROM app_video_usage WHERE user_id=? AND period_key=? FOR UPDATE',[userId,key]); if (Number(usage[0].video_used)+Number(usage[0].video_reserved)+units>limit) throw fail('VIDEO_QUOTA_EXCEEDED','سهمیه ساخت ویدیوی این دوره کافی نیست.',409); const id=randomUUID(); await c.query('UPDATE app_video_usage SET video_reserved=video_reserved+?,updated_at=NOW() WHERE user_id=? AND period_key=?',[units,userId,key]); await c.query('INSERT INTO app_video_quota_reservations (id,user_id,period_key,generation_id,quota_units,expires_at,created_at,updated_at) VALUES (?,?,?,?,?,DATE_ADD(NOW(), INTERVAL 1 DAY),NOW(),NOW())',[id,userId,key,generationId,units]); await c.commit(); return id; } catch(e){ await c.rollback(); throw e; } finally { c.release(); } },
    release: async ({ reservationId, reason = 'provider_submit_failed' }) => { const c = await db.getConnection(); try { await c.beginTransaction(); const [rows] = await c.query('SELECT user_id,period_key,quota_units,status FROM app_video_quota_reservations WHERE id=? FOR UPDATE', [reservationId]); const reservation = rows[0]; if (!reservation || reservation.status !== 'reserved') { await c.commit(); return false; } await c.query("UPDATE app_video_quota_reservations SET status='released',released_at=NOW(),release_reason=?,updated_at=NOW() WHERE id=? AND status='reserved'", [String(reason).slice(0, 100), reservationId]); await c.query('UPDATE app_video_usage SET video_reserved=GREATEST(0,video_reserved-?),updated_at=NOW() WHERE user_id=? AND period_key=?', [Number(reservation.quota_units), reservation.user_id, reservation.period_key]); await c.commit(); return true; } catch(e){ await c.rollback(); throw e; } finally { c.release(); } }
  };
}
module.exports = { createVideoQuotaService };
