import { fireEvent, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi } from 'vitest';
import VideoGenerationForm from './VideoGenerationForm';

const capability = { allowedAspectRatios:['9:16','16:9','1:1'],allowedDurations:Array.from({length:15},(_,index)=>String(index+1)),allowedQualities:[],allowedResolutions:['480p'],maxPromptLength:40 };
const profile = { id:'profile-1',profileKey:'cinematic',displayName:'واقعی و سینمایی',publicDescription:'واقعی',visualKey:'cinematic-frame',displayOrder:10,currentVersion:1 };
const props = (overrides: Partial<React.ComponentProps<typeof VideoGenerationForm>> = {}): React.ComponentProps<typeof VideoGenerationForm> => ({ capability,profile,featureEnabled:true,loading:false,error:'',onRetry:vi.fn(),prompt:'',setPrompt:vi.fn(),aspectRatio:'9:16',setAspectRatio:vi.fn(),duration:'5',setDuration:vi.fn(),resolution:'480p',inputMedia:null,inputMediaFileName:'',inputMediaPreviewUrl:'',imageInputAvailable:true,mediaUploading:false,mediaError:'',onMediaSelect:vi.fn(),onMediaRemove:vi.fn(),submitting:false,onBack:vi.fn(),onReview:vi.fn(),...overrides });

describe('VideoGenerationForm',()=>{
  it('renders loading, retry, and unavailable states',()=>{const retry=vi.fn();const {rerender}=render(<VideoGenerationForm {...props({loading:true,onRetry:retry})}/>);expect(screen.getByRole('status')).toHaveTextContent('تنظیمات معتبر');rerender(<VideoGenerationForm {...props({error:'خطای امن',onRetry:retry})}/>);fireEvent.click(screen.getByRole('button',{name:'دریافت دوباره'}));expect(retry).toHaveBeenCalledOnce();rerender(<VideoGenerationForm {...props({capability:null})}/>);expect(screen.getByText(/ساخت ویدیو از متن فعلاً/)).toBeInTheDocument();});

  it('accepts a text idea with an optional reference image before review',async()=>{const user=userEvent.setup();const onReview=vi.fn();const setPrompt=vi.fn();const {rerender}=render(<VideoGenerationForm {...props({onReview,setPrompt})}/>);expect(screen.getByText('مرحله ۲ از ۳')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'چه ویدیویی بسازیم؟'})).toBeInTheDocument();expect(screen.getByText('متن یا تصویر به ویدیو')).toBeInTheDocument();expect(screen.getByRole('button',{name:/افزودن تصویر مرجع/})).toBeInTheDocument();expect(screen.getByRole('button',{name:'ادامه و بازبینی'})).toBeDisabled();rerender(<VideoGenerationForm {...props({prompt:'یک ایدهٔ معتبر',onReview})}/>);await user.click(screen.getByRole('button',{name:'ادامه و بازبینی'}));expect(onReview).toHaveBeenCalledOnce();});

  it('fills the prompt from a safe starter idea',async()=>{const user=userEvent.setup();const setPrompt=vi.fn();render(<VideoGenerationForm {...props({setPrompt})}/>);await user.click(screen.getByRole('button',{name:/گربهٔ فضانورد/}));expect(setPrompt).toHaveBeenCalledWith(expect.stringContaining('گربهٔ فضانورد'));});

  it('offers compact 1-to-15 second settings with default 5, fixed 480p, and no audio section',()=>{const setAspectRatio=vi.fn();const setDuration=vi.fn();const {container}=render(<VideoGenerationForm {...props({prompt:'ایده معتبر',setAspectRatio,setDuration})}/>);const settings=screen.getByRole('button',{name:/تنظیمات ویدیو/});expect(settings).toHaveAttribute('aria-expanded','false');fireEvent.click(settings);expect(settings).toHaveAttribute('aria-expanded','true');fireEvent.click(screen.getByRole('button',{name:'نسبت عمودی 9:16'}));expect(setAspectRatio).toHaveBeenCalledWith('9:16');const slider=screen.getByRole('slider',{name:'مدت ویدیو به ثانیه'});expect(slider).toHaveAttribute('min','1');expect(slider).toHaveAttribute('max','15');expect(slider).toHaveValue('5');fireEvent.change(slider,{target:{value:'12'}});expect(setDuration).toHaveBeenCalledWith('12');expect(screen.getByText('480P')).toBeInTheDocument();expect(container.querySelector('.video-resolution-options')).toBeNull();expect(screen.queryByRole('switch')).toBeNull();expect(screen.queryByText('به‌زودی فعال می‌شود')).toBeNull();});

  it('passes an accepted image to the upload handler and exposes selected-image actions',async()=>{const user=userEvent.setup();const onMediaSelect=vi.fn();const {rerender}=render(<VideoGenerationForm {...props({prompt:'ایده معتبر',onMediaSelect})}/>);const file=new File(['image'],'start.png',{type:'image/png'});await user.upload(screen.getByLabelText('انتخاب تصویر مرجع برای ساخت ویدیو'),file);expect(onMediaSelect).toHaveBeenCalledWith(file);rerender(<VideoGenerationForm {...props({prompt:'ایده معتبر',inputMedia:{mediaId:'media-1',mimeType:'image/png',sizeBytes:5},inputMediaFileName:'start.png',inputMediaPreviewUrl:'blob:preview'})}/>);expect(screen.getByText('تصویر به ویدیو')).toBeInTheDocument();expect(screen.getByRole('button',{name:'تغییر تصویر'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'حذف'})).toBeInTheDocument();});
});
