import { fireEvent, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi } from 'vitest';
import VideoGenerationForm from './VideoGenerationForm';
import type { MultiImageState } from './video-generation.types';

const capability = { allowedAspectRatios:['9:16','16:9','1:1'],allowedDurations:Array.from({length:15},(_,index)=>String(index+1)),allowedQualities:[],allowedResolutions:['480p'],maxPromptLength:40,quotaUnits:2, maxReferences:7, minReferences:2, supportsImageToVideoMulti: true };
const profile = { id:'profile-1',profileKey:'cinematic',displayName:'واقعی و سینمایی',publicDescription:'واقعی',visualKey:'cinematic-frame',displayOrder:10,currentVersion:1 };
const readyImage: MultiImageState = { localId:'img-1', fileName:'portrait.jpg', previewUrl:'blob:preview', uploadStatus:'ready', mediaId:'media-1', mimeType:'image/jpeg', sizeBytes:1024 };
const emptyImages: MultiImageState[] = [];
const props = (overrides: Partial<React.ComponentProps<typeof VideoGenerationForm>> = {}): React.ComponentProps<typeof VideoGenerationForm> => ({ capability,profile,featureEnabled:true,loading:false,error:'',onRetry:vi.fn(),prompt:'',setPrompt:vi.fn(),aspectRatio:'9:16',setAspectRatio:vi.fn(),duration:'5',setDuration:vi.fn(),resolution:'480p',setResolution:vi.fn(),media:null,images:emptyImages,imagesUploading:false,multiAvailable:true,onFilesAdded:vi.fn(),onMediaFile:vi.fn(),onRemoveImage:vi.fn(),onRetryImage:vi.fn(),onReorder:vi.fn(),onRemoveMedia:vi.fn(),mediaUploading:false,mediaError:'',submitting:false,onBack:vi.fn(),onReview:vi.fn(),...overrides });

describe('VideoGenerationForm',()=>{
  it('renders loading, retry, and unavailable states',()=>{const retry=vi.fn();const {rerender}=render(<VideoGenerationForm {...props({loading:true,onRetry:retry})}/>);expect(screen.getByRole('status')).toHaveTextContent('تنظیمات معتبر');rerender(<VideoGenerationForm {...props({error:'خطای امن',onRetry:retry})}/>);fireEvent.click(screen.getByRole('button',{name:'دریافت دوباره'}));expect(retry).toHaveBeenCalledOnce();rerender(<VideoGenerationForm {...props({capability:null})}/>);expect(screen.getByText(/فعلاً توسط مدیر/)).toBeInTheDocument();});
  it('requires image and prompt before review',()=>{const onReview=vi.fn();render(<VideoGenerationForm {...props({onReview})}/>);expect(screen.getByText('مرحله ۲ از ۳')).toBeInTheDocument();expect(screen.getByText(/تصاویر را اینجا رها کنید/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'ادامه و بازبینی'})).toBeDisabled();});
  it('renders multi-image preview and exposes no provider or model controls',()=>{render(<VideoGenerationForm {...props({prompt:'یک حرکت معتبر',images:[readyImage]})}/>);expect(screen.getByRole('img',{name:/portrait.jpg/})).toHaveAttribute('src','blob:preview');expect(screen.queryByText(/bananaai|metis|openrouter|مدل ساخت ویدیو/i)).not.toBeInTheDocument();});
  it('offers a numeric 1-to-15 duration control and the currently enabled resolution',()=>{const setAspectRatio=vi.fn();const setDuration=vi.fn();const setResolution=vi.fn();render(<VideoGenerationForm {...props({prompt:'حرکت معتبر',images:[readyImage],setAspectRatio,setDuration,setResolution})}/>);fireEvent.click(screen.getByRole('button',{name:/عمودی/}));expect(setAspectRatio).toHaveBeenCalledWith('9:16');const slider=screen.getByRole('slider',{name:'مدت ویدیو به ثانیه'});expect(slider).toHaveAttribute('min','1');expect(slider).toHaveAttribute('max','15');fireEvent.change(slider,{target:{value:'12'}});expect(setDuration).toHaveBeenCalledWith('12');fireEvent.click(screen.getByRole('button',{name:'وضوح 480p'}));expect(setResolution).toHaveBeenCalledWith('480p');expect(screen.queryByRole('button',{name:'وضوح 720p'})).toBeNull();expect(screen.getByRole('button',{name:'بازگشت'})).toBeEnabled();});
  it('shows the selected image with remove action',async()=>{const user=userEvent.setup();const onRemoveImage=vi.fn();render(<VideoGenerationForm {...props({prompt:'حرکت معتبر',images:[readyImage],onRemoveImage})}/>);expect(screen.getByRole('img',{name:/portrait.jpg/})).toHaveAttribute('src','blob:preview');const removeBtn = screen.getByTitle('حذف');await user.click(removeBtn);expect(onRemoveImage).toHaveBeenCalledOnce();});
});
